DSC stack mostly ported

diff --git a/stacks/stack_dsc b/stacks/stack_dsc
--- a/stacks/stack_dsc
+++ b/stacks/stack_dsc
@@ -3,7 +3,11 @@
 if [ -z "$DEBUG" ]; then 
   set -x
 fi
-set -eu
+
+set -o pipefail  # trace ERR through pipes
+set -o errtrace  # trace ERR through 'time command' and other functions
+set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
+set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
 cd $DIR
@@ -23,6 +27,10 @@ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/
 
 ../shib_it
 stack_run_batch "../pmake" dsc.pkgsrc.txt
+# install openquicktime "by hand" (needs patch?)
 . ../setenv.sh
+which pip
 stack_run_batch  "pip install" dsc.pip.txt
+which cpanm
 stack_run_batch "cpanm" dsc.cpanm.txt
+# install File::List "by hand"
