open ssl upgrade for nuxeo

diff --git a/stacks/stack_nuxeo b/stacks/stack_nuxeo
--- a/stacks/stack_nuxeo
+++ b/stacks/stack_nuxeo
@@ -18,13 +18,28 @@ export LD_LIBRARY_PATH="${HOME}/pkg/lib:${HOME}/servers/shibboleth/lib"
 . $DIR/../setenv.sh
 
 # install pkgsrc packages
-ACCEPTABLE_LICENSES=lame-license stack_run_batch "../pmake" nuxeo.pkgsrc.txt
-#easy_install-2.7 pip==1.2.1
-pip install lxml
-pip install staller
+ACCEPTABLE_LICENSES="lame-license openssl" stack_run_batch "../pmake" nuxeo.pkgsrc.txt
+bmake PKG_OPTIONS.ffmpeg="ass lame libvpx theora vaapi vdpau vorbis x264 xvid faac opencore-amr" \
+  ACCEPTABLE_LICENSES="lame-license" \
+  -C ${HOME}/pkgsrc/multimedia/ffmpeg install
+
+# build root certificates for ssl
+if [ ! -f ${HOME}/pkg/etc/openssl/certs/mozilla-rootcert-1.pem ]; then
+    set +e
+    mozilla-rootcerts install
+    echo "cdl_build: Ignore message about 'aborting' above. Continuing..."
+    set -e
+fi
+
+#fix python path
 if [[ ! -e ${HOME}/pkg/bin/python ]]; then
     ln -s ${HOME}/pkg/bin/python2.7 ${HOME}/pkg/bin/python
 fi
+
+easy_install-2.7 pip==1.2.1
+pip install lxml
+pip install staller
+pip install https://github.com/tingletech/fixity/archive/master.tar.gz
 shib_it -p ${HOME}/servers/shibboleth -o ${HOME}/pkg -t ${HOME}/tmp
 ../roll_test_certs
 ../cdl/get_java 
